name: 🚀 Deploy Feedsport

on:
  push:
    branches:
      - main    # trigger on pushes to main (adjust as needed)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout & Node setup
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 2. Install & build
      - name: Install dependencies
        run: npm ci

      - name: Build & Export
        run: npm run build

      # 3. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # 4. Sync to S3
      - name: Sync to S3
        run: |
          aws s3 sync out/ s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete 

      # 5. Invalidate CloudFront cache
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
